theme: jekyll-theme-hacker
title: Gabriel Adams – Cybersecurity Portfolio
description: Researcher in Embedded Systems and Satellite Security | SFS Scholar
show_downloads: true  # Optional: Show a download button for repository ZIP
